LavidaCoffee/Controllers/AboutController.cs
using LavidaCoffee.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Operations;

namespace LavidaCoffee.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LavidaCoffee/Controllers/Find_UsController.cs
using LavidaCoffee.Models;
using LavidaCoffee.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LavidaCoffee.Controllers
{
    public class Find_UsController : Controller
    {
		private readonly IEventRepository _eventRepository;
		public Find_UsController(IEventRepository eventRepository)
		{
			_eventRepository = eventRepository;
		}
        public async Task<IActionResult> Index()
        {
	        Find_UsIndexViewModel model = new()
	        {
		        Events = (await _eventRepository.GetUpcomingEventsAsync()).ToList()
	        };
			return View(model);
        }

		public async Task<IActionResult> EventDetails(int id)
		{
			Find_UsEventDetailsViewModel model = new()
			{
				Event = await _eventRepository.GetEventByIdAsync(id)
			};
			if (model.Event == null)
			{
				return NotFound();
			}
			return View(model);
		}
    }
}

LavidaCoffee/Views/Shared/_EventCard.cshtml
@model Event

<div class="card skin-bg">
	<div class="card-body ms-3 me-3">
		<h3 class="card-title m-2">@Model.Title</h3>
		<h5>@Model.Date</h5>
		<p><i>@Model.Address</i></p>
		<p class="card-text">@Model.ShortDescription</p>
	</div>
	<div class="tileImage p-2 m-md-3">
		<img src="@Model.ThumbnailUrl" class="card-img-top img-fluid fixed-height-img" />
	</div>
</div>

LavidaCoffee/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
     <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="https://kit.fontawesome.com/2b102d8f12.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caprasimo&display=swap" rel="stylesheet">

    <link href="~/css/site.css" rel="stylesheet"/>
    <title>Lavida Coffee</title>
</head>
<body>
    <div class="d-flex flex-column">
        <!-- BEGIN: Header content -->
        <header>
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid pt-2 pb-2">
                    <a class="navbar-brand ms-md-5 me-md-5 ms-4" asp-controller="Home" asp-action="Index">
                        <img src="~/Images/logo.png" class="logo" alt="Lavida Coffee Logo">
                        </a>
                        <button class="navbar-toggler custom-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav text-end mb-3">
                            <li class="nav-item ms-3 me-3">
                                <a class="nav-link" aria-current="page" asp-controller="about" asp-action="Index">About us</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" drole="button" aria-expanded="false" asp-controller="Find_Us" asp-action="Index">Find us</a>
                                <ul class="dropdown-menu maroon-bg text-end border-0">
                                    <li><a class="dropdown-item nav-link maroon-bg" asp-controller="Find_us" asp-action="Index" asp-fragment="hq">Lavida HQ</a></li>
                                    <li><a class="dropdown-item nav-link maroon-bg" asp-controller="Find_us" asp-action="Index" asp-fragment="upcoming_events">Upcoming events</a></li>
                                </ul>
                            </li>
                            
                            <li class="nav-item ms-3 me-3">
                                <a class="nav-link" asp-controller="contact" asp-action="Index">Contact us</a>
                            </li>
                        </ul>
                        @await Html.PartialAsync("_LoginPartial")
                    </div>
                </div>
            </nav>
        </header>
        <!-- END: Header content -->
        <!-- BEGIN: Main content -->
        <main class="flex-grow-1 skin-bg">
            @RenderBody()
            @RenderSection("Scripts", required: false)
        </main>
        <!-- END: Main content -->
    </div>   
    
    <!-- BEGIN: Footer content -->
    <footer class="screen-height p-4 maroon-bg position-relative">
        <div class="row p-5 text-center">
            <div class="col-12 col-md-4 mb-5">
                <div class="my-auto">
                    <h3 class="mb-3">Lavida Coffee</h3>
                    <p class="m-1">Cheltenham Spa station,</p>
                    <p class="m-1">Queens Road,</p>
                    <p class="m-1">Cheltenham,</p>
                    <p class="m-1">Gloucestershire,</p>
                    <p class="m-1 mb-3">GL51 8NP</p>
                    <p class="m-1">/// forms.flying.cowboy</p>
                </div>
            </div>
            <div class="col-12 col-md-4 mb-5">
                <h3 class="mb-3">Get in touch</h3>
                <div class="my-auto">
                    <p class="m-1 mb-0">Phone</p>
                    <p class="m-1 mt-0 mb-3">+44 7768 657259</p>
                    <div class="m-1" style="text-decoration: underline;">
                        <email address="admin@@joe-lambon.dev" content="Email us" class="p-0"></email>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-4 mb-5">
                <h3 class="mb-3"> Quick links </h3>
                <div class="my-auto">
                    <p class="m-1"><a class="text-decoration-none" asp-controller="About" asp-action="Index">About us</a></p>
                    <p class="m-1"><a class="text-decoration-none" asp-controller="Find_Us" asp-action="Index" asp-fragment="upcoming_events">Upcoming events</a></p>
                    
                </div>
            </div>
            <div class="col-12 mt-5 text-center">
                <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">
                    <i class="fa-brands fa-instagram fa-2xl"></i>
                </a>
            </div>
        </div>
    </footer>
    <!-- END: Footer content -->
</body>
</html>